create table cow_country_codes (
stateabb varchar(3),
ccode int primary key,
statenme varchar(255) unique
);
alter table cow_country_codes
add constraint unique_stateabb
unique (stateabb);

create table cow_war_list (
year int,
war varchar(255),
type varchar,
code int primary key);

create table typology (
war_type_id integer primary key,
war_type varchar
);
insert into typology (war_type_id, war_type) values 
(1, 'Inter-state war'),
(2, 'Extra-state war: Colonial--conflict with colony'),
(3, 'Extra-state war: Imperial--state vs. nonstate'),
(4, 'Intra-state war: Civil war--for central control'),
(5, 'Intra-state war: Civil war--over local issues'),
(6, 'Intra-state war: Regional internal'),
(7, 'Intra-state war: Intercommunal'),
(8, 'Non-state war: In nonstate territory'),
(9, 'Non-state war: Across state borders');

create table regions (
where_fought int primary key,
region varchar);
insert into regions values
(1, 'Western Hemisphere'),
(2, 'Europe'),
(4, 'Africa'),
(6, 'Middle East'),
(7, 'Asia'),
(9, 'Oceania');
insert into regions values
(11, 'Europe & Middle East'),
(12, 'Europe & Asia'),
(13, 'Western Hemisphere & Asia'),
(14, 'Europe, Africa & Middle East'),
(15, 'Europe, Africa, Middle East & Asia'),
(16, 'Africa, Middle East, Asia & Oceania'),
(17, 'Asia & Oceania'),
(18, 'Africa & Middle East'),
(19, 'Europe, Africa, Middle East, Asia & Oceania');

alter table regions add constraint unique_region unique (region);
create table alliance_by_member (
version4id int,
ccode int references cow_country_codes(ccode),
state_name varchar,
all_st_day int,
all_st_month int,
all_st_year int,
all_end_day int,
all_end_month int,
all_end_year int,
ss_type varchar,
mem_st_day int,
mem_st_month int,
mem_st_year int,
mem_end_day	int,
mem_end_month int,
mem_end_year int,
left_censor boolean,
right_censor boolean,
defense	boolean,
neutrality boolean,
nonaggression boolean,
entente	boolean,
version double precision,
primary key (version4id, ccode, mem_st_day, mem_st_month, mem_st_year)
);

create table alliance_by_member_yearly (
version4id int,
ccode int references cow_country_codes(ccode),
state_name varchar,
all_st_day int,
all_st_month int,
all_st_year int,
all_end_day int,
all_end_month int,
all_end_year int,
ss_type varchar,
mem_st_day int,
mem_st_month int,
mem_st_year int,
mem_end_day	int,
mem_end_month int,
mem_end_year int,
left_censor boolean,
right_censor boolean,
defense	boolean,
neutrality boolean,
nonaggression boolean,
entente	boolean,
year int,
version double precision,
primary key (version4id, ccode, year));

create table alliance_by_directed (
version4id int,
ccode1 int references cow_country_codes(ccode),
state_name1	varchar,
ccode2 int references cow_country_codes(ccode),
state_name2	varchar,
dyad_st_day int,
dyad_st_month int,
dyad_st_year int,
dyad_end_day int,
dyad_end_month int,
dyad_end_year int,
left_censor boolean,
right_censor boolean,
defense	boolean,
neutrality boolean,
nonaggression boolean,
entente boolean,
version double precision,
id int primary key);

create table alliance_by_directed_yearly (
version4id int,
ccode1 int references cow_country_codes (ccode),
state_name1	varchar,
ccode2 int references cow_country_codes (ccode),
state_name2	varchar,
dyad_st_day	int,
dyad_st_month int,
dyad_st_year int,
dyad_end_day int,
dyad_end_month int,
dyad_end_year int,
left_censor boolean,
right_censor boolean,
defense	boolean,
neutrality boolean,
nonaggression boolean,
entente boolean,
year int,
version double precision,
id int primary key
);

create table alliance_by_dyad (
version4id int,
ccode1 int references cow_country_codes (ccode),
state_name1	varchar,
ccode2 int references cow_country_codes (ccode),
state_name2	varchar,
dyad_st_day	int,
dyad_st_month int,
dyad_st_year int,
dyad_end_day int,
dyad_end_month int,
dyad_end_year int,
left_censor boolean,
right_censor boolean,
defense	boolean,
neutrality boolean,
nonaggression boolean,
entente boolean,
asymetric boolean,
version double precision,
id int primary key
);


create table alliance_by_dyad_yearly (
version4id int,
ccode1 int references cow_country_codes (ccode),
state_name1	varchar,
ccode2 int references cow_country_codes (ccode),
state_name2	varchar,
dyad_st_day	int,
dyad_st_month int,
dyad_st_year int,
dyad_end_day int,
dyad_end_month int,
dyad_end_year int,
left_censor boolean,
right_censor boolean,
defense	boolean,
neutrality boolean,
nonaggression boolean,
entente boolean,
year int,
version double precision
);

create table contcol (
dyad int,
statelno int references cow_country_codes (ccode),
statelab varchar(3) references cow_country_codes (stateabb),
dependl int,
conttype int,
statehno int references cow_country_codes (ccode),
statehab varchar(3) references cow_country_codes (stateabb),
dependh	int,
begin_year int,
end_year int,
version double precision
);

create table contcold (
dyad int,
statelno int references cow_country_codes (ccode),
statelab varchar(3) references cow_country_codes (stateabb),
statehno int references cow_country_codes (ccode),
statehab varchar(3) references cow_country_codes (stateabb),
year int,
land int,
sea	int,
total int,
version double precision
);

create table contcols (
stateno	int references cow_country_codes (ccode),
stateab	varchar(3) references cow_country_codes (stateabb),
year int,
total int,
land int,
sea int,
version double precision
);

create table contdir (
dyad int,
statelno int references cow_country_codes (ccode),
statelab varchar(3) references cow_country_codes (stateabb),
statehno int references cow_country_codes (ccode),
statehab varchar(3) references cow_country_codes (stateabb),
conttype int,
begin_month int,
end_month int,
notes varchar,
version double precision
);

create table contdird (
dyad int,
state1no int references cow_country_codes (ccode),
state1ab varchar(3) references cow_country_codes (stateabb),
state2no int references cow_country_codes (ccode),
state2ab varchar(3) references cow_country_codes (stateabb),
year int,
conttype int,
version double precision
);

create table contdirs (
stateno	int references cow_country_codes (ccode),
stateab	varchar(3) references cow_country_codes (stateabb),
year int,
total int,
land int,
sea int,
version double precision	
);

create table dcad_main (
ccode1 int references cow_country_codes (ccode),
cowName1 varchar(3),
ccode2 int references cow_country_codes (ccode),
cowName2 varchar(3),
signDay int,
signMonth int,
signYear int,
EIFDay int,
EIFMonth int,
EIFYear int,
type varchar,
category1 varchar,
category2 varchar,
category3 varchar,
span int,
renewType int,
renewYears int,
terminated int,
durationActual int,
endYearEstimate int,
asymmetry int,
categoryConf varchar,
UNTS int,
fullText varchar,
sourceType varchar,
source varchar,
factivaConf int,
factivaSign int,
factivaEIF int,
DCAid varchar);
alter table dcad_main
add primary key (dcaid);

create table dcad_dyadic (
ccode1 int references cow_country_codes (ccode),
abbrev1	varchar(3) references cow_country_codes (stateabb),
ccode2 int references cow_country_codes (ccode),
abbrev2 varchar(3) references cow_country_codes (stateabb),
year int,
dcaGeneralV1 int,
dcaGeneralV2 int,
dcaSectorV1 int,
dcaSectorV2 int,
dcaAnyV1 int,
dcaAnyV2 int);

create table directed_dyadic_war (
warnum int references cow_war_list (code),
disno int,
dyindex	varchar,
statea int references cow_country_codes (ccode),
stateb int references cow_country_codes (ccode),
warstrtmnth	int,
warstrtday int,
warstrtyr int,
warendmnth int,
warenday int,
warendyr int,
year int,
warolea int,
waroleb int,
wardyadrolea int,
wardyadroleb int,
outcomea int,
batdtha int,
batdthb int,
changes_1 int,
changes_2 int,
batdths int,
durindx int
);

create table dyadic_format_v3 (
ccode1 int references cow_country_codes (ccode),
country1 varchar,
ccode2 int references cow_country_codes (ccode),
country2 varchar,
year int,
state varchar,
AALCO int,
AATA int,
ACDT int,
ACPEU int,
ANZUS int,
AP int,
APT int,
BALTBAT int,
BC int,
BENELUX int,
BSEC int,
CACI int,
CBSS int,
CCNR int,
CComm int,
CENTO int,
CHSTEA int,
CIS int,
COE int,
ComSec int,
EAPC int,
EIPA int,
ESA int,
Entente int,
G15 int,
G24 int,
G3 int,
GLACSEC int,
IADefB int,
IAHC int,
IARHC int,
IASAJ int,
ICAmO int,
ICCILMB int,
ICivDO int,
IDC	int,
IOCom int,
IOMig int,
ITTO int,
IUPIP int,
LOAS int,
LoN int,
MFO int,
NAM int,
NATO int,
NCM int,
NordC int,
OAS int,
OAU int,
OCAS int,
OCR int,
OPANAL int,
OSCE int,
PAHO int,
PCA int,
PIF int,
PMAESA int,
RCC int,
RIOgroup int,
RepCom int,
SAARC int,
SCHENGEN int,
SEATO int,
SPC int,
UN int,
USP int,
WCDC int,
WEU int,
WPact int,
Wassen int,
AU int,
CSTO int,
Corg int,
EIP int,
IORARC int,
UM int,
SWPD int,
SCO int,
RECSA int,
BOBP int,
CICA int,
FEC int,
IRU int,
IUIC int,
PAP int,
RCFC int,
SEGIB int,
ACCT int,
ACI int,
ACML int,
ACSO int,
AFTE int,
ARCAL int,
ASATP int,
ASCBC int,
ASEF int,
AmCC int,
AralSea int,
ArticC int,
BCSC int,
BIISEF int,
BIONET int,
CAB int,
CABI int,
CAIPA int,
CAMES int,
CBI int,
CELC int,
CMHASG int,
COLOMBO int,
CONFEJES int,
COSAVE int,
CPAB int,
CPSC int,
CTCAf int,
CWGC int,
CXC int,
Danube int,
ECCD int,
EFCC int,
EFILWC int,
EMBC int,
EMBL int,
EMPPO int,
ESO int,
ETF int,
EUFMD int,
EURATOM int,
GBACT int,
GCRSNC int,
GEF int,
IABE int,
IABath int,
IACI int,
IACS int,
IACSS int,
IACW int,
IAEA int,
IAIAS int,
IAMLO int,
IAPhy int,
IARadiO int,
IARuhr int,
IATSJ int,
IBE int,
IBI int,
IBIER int,
IBPMP int,
ICAO int,
ICCROM int,
ICCS int,
ICDR int,
ICES int,
ICHRB int,
ICMMP int,
ICPRP int,
ICRI int,
ICRPBC int,
ICTM int,
IEC int,
IES	int,
IEXB int,
IHO	int,
IIE int,
ILO	int,
IMBSlav int,
IMC int,
IMI int,
INCAP int,
INFSMK int,
INTERPOL int,
IOEz int,
IOLM int,
IOPH int,
IPedI int,
IPentC int,
IPhyL int,
IRLCS int,
IRO int,
ISA int,
ISHREST int,
ISUPT int,
ITCC int,
ITCLE int,
IUPLAW int,
JALAAO int,
JINR int,
JNOLCRH int,
LACAC int,
LACP int,
LAEO int,
LAIEC int,
LATIN int,
LCBC int,
MCPTTC int,
MCWCASM int,
MWN int,
Montreal int,
NAPPO int,
NASCO int,
NCRR int,
NEAFC int,
NPAFC int,
NPFSC int,
NTSC int,
OCCEDCA int,
OIC int,
OMDKR int,
OSLO int,
OSPAR int,
PAIGH int,
PC int,
PCSP int,
PICES int,
PICS int,
PSNARCO int,
RCAELA int,
RIMMO int,
RIOPPAH int,
SACEP int,
SCAf int,
SCH int,
SEAMEO int,
SWAPU int,
Turksoy int,
UNESCO int,
VASAB int,
WAEC int,
WAHC int,
WHO int,
WMO	int,
ALSF int,
AMCOW int,
CBFP int,
CSLF int,
CfRN int,
GEO int,
GHSI int,
IAII int,
ICPTU int,
IGCC int,
INPFC int,
IRENA int,
ISuC int,
WAHO int,
PAPU int,
MAOCN int,
MARRI int,
NPI int,
NWHF int,
AfricaRice int,
BORGIP int,
CILSS int,
EURAMET int,
ICFAM int,
IIFEO int,
IIWEE int,
ISRBC int,
ITRO int,
NAFO int,
NVC int,
OIV int,
PIBAC int,
VALDIVIA int,
UNIDROIT int,
AAAID int,
AACB int,
AARO int,
AATPO int,
ABEDA int,
ABEPSEAC int,
ACC int,
ACP int,
ACS int,
ACSSRB int,
ACU int,
AFESD int,
AFEXIMB int,
AFGEC int,
AFPU int,
AFRAND int,
AGC int,
AGPUNDO int,
AIC int,
AIDC int,
AIDO int,
AIOEC int,
AIPO int,
ALO int,
AMCO int,
AMF int,
AMIPO int,
AMPTU int,
AMSC int,
AMU int,
AOAD int,
AOCRS int,
AOMR int,
AOPU int,
APCC int,
APEC int,
APFIC int,
APIBD int,
APO	int,
APPA int,
APTU int,
ARC int,
ARIPO int,
ARPU int,
ASBLAC int,
ASCRubber int,
ASEAN int,
ASECNA int,
ASPAC int,
ATO int,
ATPC int,
AVRDC int,
AfDB int,
AfrOPDA int,
Africare int,
Andean int,
AsDB int,
BIPM int,
BIS int,
BNDP int,
BONN int,
CAAD int,
CAARC int,
CACB int,
CAEC int,
CAECC int,
CAMRSD int,
CAMSF int,
CARICOM int,
CARIFTA int,
CARII int,
CATC int,
CCOM int,
CCPA int,
CDB int,
CEAO int,
CEC int,
CEEPN int,
CEFTA int,
CEI int,
CEMAC int,
CEPGL int,
CERN int,
CFATF int,
CFC	int,
CIFC int,
CIMA int,
CMAEC int,
CMAOC int,
CMEA int,
COMESA int,
COPTAC int,
CPU int,
CTO int,
ComAB int,
DBGLS int,
DLCOEA int,
EACM int,
EACSO int,
EADB int,
EAPO int,
EBRD int,
ECB int,
ECCA int,
ECCAS int,
ECCB int,
ECCM int,
ECCPIF int,
ECO int,
ECOWAS int,
ECPTA int,
ECSC int,
EEC int,
EFTA int,
EIB	int,
ELDO int,
EMB int,
EMI	int,
EPA int,
EPFSC int,
EPO int,
ESRO int,
EU int,
EUROCONTROL int,
EUROFIMA int,
EUROMET int,
FAO int,
FDIPLAC int,
GATT int,
GCC int,
GOIC int,
HCPIL int,
IACB int,
IADB int,
IAFC int,
IAIC int,
IAIGC int,
IALong int,
IARA int,
IAS int,
IATB int,
IATTC int,
IBA int,
IBCS int,
IBEC int,
IBRD int,
ICAC int,
ICAI int,
ICC int,
ICCEC int,
ICCO int,
ICCSLT int,
ICNC int,
ICNWAF int,
ICSE int,
ICSEAF int,
ICSG int,
ICfO int,
IChemO int,
IComO int,
IEA int,
IFAD int,
IFC int,
IFCA int,
IGAD int,
IGC int,
IIA int,
IICom int,
IIF int,
IJO int,
ILZSG int,
IMF int,
IMO int,
IMSO int,
INFOFISH int,
INRO int,
INSG int,
INTELSAT int,
IOATHRE int,
IOOC int,
IOPCF int,
IOcC int,
IPC int,
IPI int,
IPrizeC int,
IRSG int,
ISB	int,
ISDB int,
ITC int,
ITPA int,
ITU int,
ITVRC int,
IUPCT int,
IUPNVP int,
IUPR int,
IVWO int,
IWSG int,
IWhale int,
Iocean int,
LAFDO int,
LAFTA int,
LAIA int,
LGIDA int,
MIGA int,
MRU int,
Mercosur int,
NACAP int,
NAFTA int,
NCTR int,
NDF int,
NERC int,
NIB int,
NRC int,
OAPEC int,
OCAM int,
OECD int,
OECS int,
OEEC int,
OPEC int,
OTIF int,
PAHC int,
PCB int,
PED int,
PIARC int,
PIPD int,
PTASEA int,
PUASP int,
RASCOM int,
RadioU int,
SAAFA int,
SACU int,
SADC int,
SADCC int,
SAMI int,
SARTC int,
SCA int,
SELA int,
SICA int,
SIECA int,
SITTDEC int,
SRDO int,
SugU int,
TCRMG int,
UASC int,
UBEC int,
UDEAC int,
UEMOA int,
UIUCV int,
UKDWD int,
UMAC int,
UMOA int,
UNIDO int,
UPU int,
WCO int,
WIPO int,
WNF int,
WTO int,
WTOURO int,
ACWL int,
AFSPC int,
AITIC int,
BS int,
D8 int,
EAC int,
EAEC int,
EPU int,
ERIA int,
AFRISTAT int,
OMVG int);
alter table dyadic_format_v3
add primary key (ccode1, ccode2, year);

create table extra_state_war_data (
war_num int,
war_name varchar,
war_type int,
ccode1 int,
side_a varchar,
ccode2 int,
side_b varchar,
start_month_1 int,
start_day_1 int,
start_year_1 int,
end_month_1 int,
end_day_1 int,
end_year_1 int,
start_month_2 int,
start_day_2 int,
start_year_2 int,
end_month_2 int,
end_day_2 int,
end_year_2 int,
initiator int,
interven int,
trans_from int,
outcome int,
trans_to int,
where_fought int,
bat_death int,
nonstate_deaths int,
version double precision
);
alter table extra_state_war_data
add constraint fk_war_num foreign key (war_num)
references cow_war_list (code);
alter table extra_state_war_data
add constraint fk_ccode1 foreign key (ccode1)
references cow_country_codes (ccode);
alter table extra_state_war_data
add constraint fk_ccode2 foreign key (ccode2)
references cow_country_codes (ccode);
alter table extra_state_war_data
add constraint fk_war_type foreign key (war_type)
references typology (war_type_id);
alter table extra_state_war_data
add constraint fk_where_fought foreign key (where_fought)
references regions (where_fought);

/*CREATE TABLE inter_state_war_data
(
    id integer NOT NULL,
    WarNum integer NOT NULL references cow_war_list (code),
    WarName character varying,
    WarType integer references typology (war_type_id),
    ccode integer NOT NULL references cow_country_codes (ccode),
    StateName character varying,
    Side integer,
    StartMonth1 integer,
    StartDay1 integer,
    StartYear1 integer,
    EndMonth1 integer,
    EndDay1 integer,
    EndYear1 integer,
    StartMonth2 integer,
    StartDay2 integer,
    StartYear2 integer,
    EndMonth2 integer,
    EndDay2 integer,
    EndYear2 integer,
    TransFrom integer[],
    WhereFought integer references regions (where_fought),
    Initiator integer,
    Outcome integer,
    TransTo integer,
    BatDeath integer,
    Version double precision,
    CONSTRAINT inter_state_war_data_pkey PRIMARY KEY (id)
);*/

CREATE TABLE public.inter_state_war_data
(
    id integer NOT NULL,
    warnum integer NOT NULL,
    warname character varying COLLATE pg_catalog."default",
    wartype integer,
    ccode integer NOT NULL,
    statename character varying COLLATE pg_catalog."default",
    side integer,
    startmonth1 integer,
    startday1 integer,
    startyear1 integer,
    endmonth1 integer,
    endday1 integer,
    endyear1 integer,
    startmonth2 integer,
    startday2 integer,
    startyear2 integer,
    endmonth2 integer,
    endday2 integer,
    endyear2 integer,
    transfrom integer[],
    wherefought integer,
    initiator integer,
    outcome integer,
    transto integer,
    batdeath integer,
    version double precision,
    CONSTRAINT inter_state_war_data_pkey PRIMARY KEY (id),
    CONSTRAINT inter_state_war_data_ccode_fkey FOREIGN KEY (ccode)
        REFERENCES public.cow_country_codes (ccode) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT inter_state_war_data_warnum_fkey FOREIGN KEY (warnum)
        REFERENCES public.cow_war_list (code) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT inter_state_war_data_wartype_fkey FOREIGN KEY (wartype)
        REFERENCES public.typology (war_type_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT inter_state_war_data_wherefought_fkey FOREIGN KEY (wherefought)
        REFERENCES public.regions (where_fought) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public.inter_state_war_data
    OWNER to pbl;

create table intra_state_war_data (
war_num int,
war_name varchar,
war_type int,
ccode_a int,
side_a varchar,
ccode_b int,
side_b varchar,
intnl boolean,
start_month_1 int,
start_day_1 int,
start_year_1 int,
end_month_1 int,
end_day_1 int,
end_year_1 int,
start_month_2 int,
start_day_2 int,
start_year_2 int,
end_month_2 int,
end_day_2 int,
end_year_2 int,
trans_from int,
where_fought int,
initiator varchar,
outcome int,
trans_to int,
side_a_deaths int,
side_b_deaths int,
version double precision,
id int primary key);
alter table intra_state_war_data
add constraint fk_ccode_a foreign key (ccode_a)
references cow_country_codes (ccode);
alter table intra_state_war_data
add constraint fk_ccode_b foreign key (ccode_b)
references cow_country_codes (ccode);
alter table intra_state_war_data
add constraint fk_war_type foreign key (war_type)
references typology (war_type_id);
alter table intra_state_war_data
add constraint fk_war_num foreign key (war_num)
references cow_war_list (code);

create table mida (
dispnum3 int,
dispnum4 int,
stday int,
stmon int,
styear int,
endday int,
endmon int,
endyear int,
outcome int,
settle int,
fatality int,
fatalpre int,
maxdur int,
mindur int,
hiact int,
hostlev int,
recip int,
numa int,
numb int,
link1 varchar,
link2 varchar,
link3 varchar,
ongo2010 boolean,
version double precision);

create table midb (
dispnum3 int,
dispnum4 int,
stabb varchar(3),
ccode int,
stday int,
stmon int,
styear int,
endday int,
endmon int,
endyear int,
sidea int,
revstate int,
revtype1 int,
revtype2 int,
fatality int,
fatalpre int,
hiact int,
hostlev int,
orig int,
version double precision
);

create table midi (
dispnum3 int,
incidnum3 int,
dispnum4 int,
incidnum4 int,
stday int,
stmon int,
styear int,
endday int,
endmon int,
endyear int,
duration int,
tbi int,
fatality int,
fatalpre int,
action int,
hostlev int,
numa int,
revtype1 int,
revtype2 int,
version double precision
);

create table midp (
dispnum3 int,
incidnum3 int,
dispnum4 int,
incidnum4 int,
stabb varchar(3),
ccode int,
stday int,
stmon int,
styear int,
endday int,
endmon int,
endyear int,
insidea int,
sidea int,
fatality int,
fatalpre int,
action int,
hostlev int,
revtype1 int,
revtype2 int,
version double precision
);

create table midloca (
year int,
dispnum	int,
midloc2_location varchar,
midloc2_measuringpoint varchar,
midloc2_xlongitude double precision,
midloc2_ylatitude double precision,
midloc2_precision int,
midloc2_howobtained varchar,
midloc2_precision_comment varchar,
midloc2_general_comment	varchar,
priogrid_cell int,
midloc11_location varchar,
midloc11_midlocmeasuringpoint varchar,
midloc11_latitude double precision,
midloc11_longitude double precision,
midloc11_precision int
);

create table midloci (
year int,
dispnum	int,
incidnum int,
midloc2_location varchar,
midloc2_measuringpoint varchar,
midloc2_xlongitude double precision,
midloc2_ylatitude double precision,
midloc2_precision int,
onset boolean,
midloc2_howobtained varchar,
midloc2_precision_comment varchar,
midloc2_general_comment	varchar,
priogrid_cell int,
midloc11_location varchar,
midloc11_midlocmeasuringpoint varchar,
midloc11_latitude double precision,
midloc11_longitude double precision,
midloc11_precision int);

create table nmc5 (
stateabb varchar(3),
ccode int,
year int,
milex int,
milper int,
irst int,
pec int,
tpop double precision,
upop double precision,
cinc double precision,
version int
);
alter table nmc5 add primary key (ccode, year);
alter table nmc5 add constraint fk_ccode foreign key (ccode)
references cow_country_codes (ccode);
alter table nmc5 add constraint fk_stateabb foreign key (stateabb)
references cow_country_codes (stateabb);

create table territorial_change_data (
year int,
month int,
gainer int,
gaintype int,
procedur int,
entity int,
contgain int,
area double precision,
pop int,
portion	int,
loser int,
losetype int,
contlose int,
entry int,
exit int,
number int,
indep int,
conflict int,
version double precision,
id serial primary key
);

create table trade_national (
ccode int references cow_country_codes (ccode),
statename varchar,
stateabb varchar(3) references cow_country_codes (stateabb),
year int,
imports double precision,
exports double precision,
alt_imports double precision,
alt_exports	double precision,
source1	double precision,
source2 double precision,
version double precision
);
alter table trade_national
add primary key (ccode, year);

create table trade_dyadic (
ccode1 int references cow_country_codes (ccode),
ccode2 int references cow_country_codes (ccode),
year int,
importer1 varchar,
importer2 varchar,
flow1 numeric,
flow2 numeric,
smoothflow1 numeric,
smoothflow2 numeric,
smoothtotrade numeric,
spike1 numeric,
spike2 numeric,
dip1 numeric,
dip2 numeric,
trdspike numeric,
tradedip numeric,
bel_lux_alt_flow1 numeric,
bel_lux_alt_flow2 numeric,
china_alt_flow1 numeric,
china_alt_flow2 numeric,
source1 numeric,
source2 numeric,
version double precision
);
alter table trade_dyadic
add primary key (ccode1, ccode2, year);

CREATE TABLE wrp_global
(
    year integer,
    chrstprot integer,
    chrstcat integer,
    chrstorth integer,
    chrstang integer,
    chrstothr integer,
    chrstgen integer,
    judorth integer,
    jdcons integer,
    judref integer,
    judothr integer,
    judgen integer,
    islmsun integer,
    islmshi integer,
    islmibd integer,
    islmnat integer,
    islmalw integer,
    islmahm integer,
    islmothr integer,
    islmgen integer,
    budmah integer,
    budthr integer,
    budothr integer,
    budgen integer,
    zorogen integer,
    hindgen integer,
    sikhgen integer,
    shntgen integer,
    bahgen integer,
    taogen integer,
    jaingen integer,
    confgen integer,
    syncgen integer,
    anmgen integer,
    nonrelig integer,
    othrgen integer,
    sumrelig bigint,
    pop bigint,
    worldpop bigint,
    chrstprotpct double precision,
    chrstcatpct double precision,
    chrstorthpct double precision,
    chrstangpct double precision,
    chrstothrpct double precision,
    chrstgenpct double precision,
    judorthpct double precision,
    judconspct double precision,
    judrefpct double precision,
    judothrpct double precision,
    judgenpct double precision,
    islmsunpct double precision,
    islmshipct double precision,
    islmibdpct double precision,
    islmnatpct double precision,
    islmalwpct double precision,
    islmahmpct double precision,
    islmothrpct double precision,
    islmgenpct double precision,
    budmahpct double precision,
    budthrpct double precision,
    budothrpct double precision,
    budgenpct double precision,
    zorogenpct double precision,
    hindgenpct double precision,
    sikhgenpct double precision,
    shntgenpct double precision,
    bahgenpct double precision,
    taogenpct double precision,
    jaingenpct double precision,
    confgenpct double precision,
    syncgenpct double precision,
    anmgenpct double precision,
    nonreligpct double precision,
    othrgenpct double precision,
    sumreligpct double precision,
    ptctotal double precision,
    version double precision,
    CONSTRAINT wrp_global_pkey PRIMARY KEY (year)
);

CREATE TABLE wrp_national
(
    year integer NOT NULL references wrp_global (year),
    state integer NOT NULL references cow_country_codes (ccode),
    name character varying(3) references cow_country_codes (stateabb),
    chrstprot integer,
    chrstcat integer,
    chrstorth integer,
    chrstang integer,
    chrstothr integer,
    chrstgen integer,
    judorth integer,
    jdcons integer,
    judref integer,
    judothr integer,
    judgen integer,
    islmsun integer,
    islmshi integer,
    islmibd integer,
    islmnat integer,
    islmalw integer,
    islmahm integer,
    islmothr integer,
    islmgen integer,
    budmah integer,
    budthr integer,
    budothr integer,
    budgen integer,
    zorogen integer,
    hindgen integer,
    sikhgen integer,
    shntgen integer,
    bahgen integer,
    taogen integer,
    jaingen integer,
    confgen integer,
    syncgen integer,
    anmgen integer,
    nonrelig integer,
    othrgen integer,
    sumrelig integer,
    pop integer,
    chrstprotpct double precision,
    chrstcatpct double precision,
    chrstorthpct double precision,
    chrstangpct double precision,
    chrstothrpct double precision,
    chrstgenpct double precision,
    judorthpct double precision,
    judconspct double precision,
    judrefpct double precision,
    judothrpct double precision,
    judgenpct double precision,
    islmsunpct double precision,
    islmshipct double precision,
    islmibdpct double precision,
    islmnatpct double precision,
    islmalwpct double precision,
    islmahmpct double precision,
    islmothrpct double precision,
    islmgenpct double precision,
    budmahpct double precision,
    budthrpct double precision,
    budothrpct double precision,
    budgenpct double precision,
    zorogenpct double precision,
    hindgenpct double precision,
    sikhgenpct double precision,
    shntgenpct double precision,
    bahgenpct double precision,
    taogenpct double precision,
    jaingenpct double precision,
    confgenpct double precision,
    syncgenpct double precision,
    anmgenpct double precision,
    nonreligpct double precision,
    othrgenpct double precision,
    sumreligpct double precision,
    total double precision,
    dualrelig double precision,
    datatype integer,
    sourcereliab integer,
    recreliab integer,
    reliabilevel character varying(6),
    version double precision,
    sourcecode double precision,
    CONSTRAINT wrp_national_pkey PRIMARY KEY (year, state)
);

CREATE TABLE wrp_regional
(
    year integer NOT NULL references wrp_global (year),
    region character varying references regions (region),
    chrstprot integer,
    chrstcat integer,
    chrstorth integer,
    chrstang integer,
    chrstothr integer,
    chrstgen integer,
    judorth integer,
    jdcons integer,
    judref integer,
    judothr integer,
    judgen integer,
    islmsun integer,
    islmshi integer,
    islmibd integer,
    islmnat integer,
    islmalw integer,
    islmahm integer,
    islmothr integer,
    islmgen integer,
    budmah integer,
    budthr integer,
    budothr integer,
    budgen integer,
    zorogen integer,
    hindgen integer,
    sikhgen integer,
    shntgen integer,
    bahgen integer,
    taogen integer,
    jaingen integer,
    confgen integer,
    syncgen integer,
    anmgen integer,
    nonrelig integer,
    othrgen integer,
    sumrelig bigint,
    pop bigint,
    worldpop bigint,
    chrstprotpct double precision,
    chrstcatpct double precision,
    chrstorthpct double precision,
    chrstangpct double precision,
    chrstothrpct double precision,
    chrstgenpct double precision,
    judorthpct double precision,
    judconspct double precision,
    judrefpct double precision,
    judothrpct double precision,
    judgenpct double precision,
    islmsunpct double precision,
    islmshipct double precision,
    islmibdpct double precision,
    islmnatpct double precision,
    islmalwpct double precision,
    islmahmpct double precision,
    islmothrpct double precision,
    islmgenpct double precision,
    budmahpct double precision,
    budthrpct double precision,
    budothrpct double precision,
    budgenpct double precision,
    zorogenpct double precision,
    hindgenpct double precision,
    sikhgenpct double precision,
    shntgenpct double precision,
    bahgenpct double precision,
    taogenpct double precision,
    jaingenpct double precision,
    confgenpct double precision,
    syncgenpct double precision,
    anmgenpct double precision,
    nonreligpct double precision,
    othrgenpct double precision,
    sumreligpct double precision,
    totalpct double precision,
    totregpct double precision,
    version double precision,
    CONSTRAINT wrp_regional_pkey PRIMARY KEY (year, region)
);

CREATE TABLE states2016
(
    stateabb character varying(3) references cow_country_codes (stateabb),
    ccode integer NOT NULL references cow_country_codes (ccode),
    statenme character varying(255),
    styear integer NOT NULL,
    stmonth integer,
    stday integer,
    endyear integer,
    endmonth integer,
    endday integer,
    version integer,
    CONSTRAINT states2016_pkey PRIMARY KEY (ccode, styear)
);

CREATE TABLE system2016
(
    stateabb character varying(3) references cow_country_codes (stateabb),
    ccode integer references cow_country_codes (ccode),
    year integer,
    version integer,
    id serial,
    CONSTRAINT system2016_pkey PRIMARY KEY (id)
);

CREATE TABLE majors2016
(
    stateabb character varying(3) references cow_country_codes (stateabb),
    ccode integer NOT NULL references cow_country_codes (ccode),
    styear integer NOT NULL,
    stmonth integer,
    stday integer,
    endyear integer,
    endmonth integer,
    endday integer,
    version integer,
    CONSTRAINT majors2016_pkey PRIMARY KEY (ccode, styear)
);

CREATE TABLE entities
(
    entity_no integer,
    name character varying COLLATE pg_catalog."default",
    startyear integer,
    endyear integer,
    ending_political_status character varying COLLATE pg_catalog."default",
    id serial,
    CONSTRAINT entities_pkey PRIMARY KEY (id)
);


create table igo_year_format (
id INT,
ioname VARCHAR,
orgname VARCHAR,
year INT,
afghanistan INT,
albania INT,
algeria INT,
andorra INT,
angola INT,
antiguabarbuda INT,
argentina INT,
armenia INT,
australia INT,
austria INT,
austriahungary INT,
azerbaijan INT,
baden INT,
bahamas INT,
bahrain INT,
bangladesh INT,
barbados INT,
bavariaelect INT,
belarus INT,
belgium INT,
belize INT,
benin INT,
bhutan INT,
bolivia INT,
bosnia INT,
botswana INT,
brazil INT,
brunei INT,
bulgaria INT,
burkinafaso INT,
burundi INT,
car INT,
cambodia INT,
cameroon INT,
canada INT,
capeverde INT,
chad INT,
chile INT,
china INT,
colombia INT,
comoros INT,
congobrazz INT,
costarica INT,
croatia INT,
cuba INT,
cyprus INT,
czechrep INT,
czechoslovakia INT,
denmark INT,
djibouti INT,
domrepublic INT,
dominica INT,
egermany INT,
etimor INT,
ecuador INT,
egypt INT,
elsalvador INT,
eqguinea INT,
eritrea INT,
estonia INT,
ethiopia INT,
fyromacedonia INT,
fiji INT,
finland INT,
france INT,
gabon INT,
gambia INT,
georgia INT,
germany INT,
ghana INT,
greece INT,
grenada INT,
guatemala INT,
guinea INT,
guineabissau INT,
guyana INT,
haiti INT,
hanover INT,
hesseelect INT,
hessegrand INT,
honduras INT,
hungary INT,
iceland INT,
india INT,
indonesia INT,
iran INT,
iraq INT,
ireland INT,
israel INT,
italy INT,
ivorycoast INT,
jamaica INT,
japan INT,
jordan INT,
kazakhstan INT,
kenya INT,
kiribati INT,
korea INT,
kosovo INT,
kuwait INT,
kyrgyzstan INT,
laos INT,
latvia INT,
lebanon INT,
lesotho INT,
liberia INT,
libya INT,
liechtenstein INT,
lithuania INT,
luxembourg INT,
madagascar INT,
malawi INT,
malaysia INT,
maldives INT,
mali INT,
malta INT,
marshallis INT,
mauritania INT,
mauritius INT,
mecklenburg INT,
mexico INT,
micronesiafs INT,
modena INT,
moldova INT,
monaco INT,
mongolia INT,
morocco INT,
montenegro INT,
mozambique INT,
myanmar INT,
namibia INT,
nauru INT,
nepal INT,
netherlands INT,
newzealand INT,
nicaragua INT,
niger INT,
nigeria INT,
nokorea INT,
norway INT,
nyemen INT,
oman INT,
pakistan INT,
palau INT,
panama INT,
papalstates INT,
papuanewguinea INT,
paraguay INT,
parma INT,
peru INT,
philippines INT,
poland INT,
portugal INT,
qatar INT,
romania INT,
russia INT,
rwanda INT,
svietnam INT,
syemen INT,
sanmarino INT,
saotome INT,
saudiarabia INT,
saxony INT,
senegal INT,
seychelles INT,
sierraleone INT,
singapore INT,
slovakia INT,
slovenia INT,
soafrica INT,
sokorea INT,
sosudan INT,
solomonis INT,
somalia INT,
spain INT,
srilanka INT,
stkitts INT,
stlucia INT,
stvincent INT,
sudan INT,
suriname INT,
swaziland INT,
sweden INT,
switzerland INT,
syria INT,
taiwan INT,
tajikistan INT,
tanzania INT,
thailand INT,
togo INT,
tonga INT,
trinidad INT,
tunisia INT,
turkey INT,
turkmenistan INT,
tuscany INT,
tuvalu INT,
twosicilies INT,
uae INT,
uk INT,
usa INT,
uganda INT,
ukraine INT,
uruguay INT,
uzbekistan INT,
vanuatu INT,
venezuela INT,
vietnam INT,
wgermany INT,
wsamoa INT,
wurtenburg INT,
yemen INT,
yugoslaviaserb INT,
zaire INT,
zambia INT,
zanzibar INT,
zimbabwe INT,
sdate INT,
deaddate INT,
dead INT,
integrated INT,
replaced INT,
longorgname VARCHAR,
ionum INT,
igocode INT,
version DOUBLE PRECISION,
accuracyofpre1965membershipdates VARCHAR,
sourcesandnotes VARCHAR,
imputed INT,
political INT,
social INT,
economic INT);
alter table igo_year_format
add primary key (ioname, year);

alter table dyadic_format_v3
rename to igo_dyadic_format;

create table diplomatic_exchange (
id INT,
ccode1 INT REFERENCES cow_country_codes (ccode),
ccode2 INT REFERENCES cow_country_codes (ccode),
year INT,
DR_at_1 INT,
DR_at_2 INT,
DE INT,
version DOUBLE PRECISION
);

CREATE TABLE nmc5_supp (
statenme VARCHAR,
stateabb VARCHAR(3) REFERENCES cow_country_codes (stateabb),
ccode INT REFERENCES cow_country_codes (ccode),
year INT,
milex INT,
milexsource	VARCHAR,
milexnote VARCHAR,
milper INT,
milpersource VARCHAR,
milpernote VARCHAR,
irst INT,
irstsource VARCHAR,
irstnote VARCHAR,
irstqualitycode VARCHAR(1),
irstanomalycode VARCHAR(1),
pec INT,
pecsource VARCHAR,
pecnote VARCHAR,
pecqualitycode VARCHAR(1),
pecanomalycode VARCHAR,
tpop DOUBLE PRECISION,
tpopsource VARCHAR,
tpopnote VARCHAR,
tpopqualitycode VARCHAR(1),
tpopanomalycode VARCHAR(1),
upop DOUBLE PRECISION,
upopsource VARCHAR,
upopnote VARCHAR,
upopqualitycode	VARCHAR(1),
upopanomalycode VARCHAR(1),
upopgrowth DOUBLE PRECISION,
upopgrowthsource VARCHAR,
cinc DOUBLE PRECISION,
version INT,
PRIMARY KEY (ccode, year)
);

CREATE TABLE non_state_war_data (
WarNum INT PRIMARY KEY,
WarName	VARCHAR,
WarType	INT REFERENCES typology (war_type_id),
WhereFought	INT REFERENCES regions (where_fought),
SideA1 VARCHAR,
SideA2 VARCHAR,
SideB1 VARCHAR,
SideB2 VARCHAR,
SideB3 VARCHAR,
SideB4 VARCHAR,
SideB5 VARCHAR,
StartYear INT,
StartMonth INT,
StartDay INT,
EndYear INT,
EndMonth INT,
EndDay INT,
Initiator VARCHAR(1),
TransFrom INT,
TransTo INT,
Outcome INT,
SideADeaths INT,
SideBDeaths INT,
TotalCombatDeaths INT,
Version DOUBLE PRECISION
);

CREATE TABLE igo_state_year_format (
ccode INT,
year INT,
state VARCHAR,
aaaid INT,
aacb INT,
aalco INT,
aaro INT,
aata INT,
aatpo INT,
abeda INT,
abepseac INT,
acc INT,
acct INT,
acdt INT,
aci INT,
acml INT,
acp INT,
acpeu INT,
acs INT,
acso INT,
acssrb INT,
acu INT,
acwl INT,
afesd INT,
afeximb INT,
afgec INT,
afpu INT,
afrand INT,
afristat INT,
afspc INT,
afte INT,
agc INT,
agpundo INT,
aic INT,
aidc INT,
aido INT,
aioec INT,
aipo INT,
aitic INT,
alo INT,
alsf INT,
amco INT,
amcow INT,
amf INT,
amipo INT,
amptu INT,
amsc INT,
amu INT,
anzus INT,
aoad INT,
aocrs INT,
aomr INT,
aopu INT,
ap INT,
apcc INT,
apec INT,
apfic INT,
apibd INT,
apo INT,
appa INT,
apt INT,
aptu INT,
arc INT,
arcal INT,
aripo INT,
arpu INT,
asatp INT,
asblac INT,
ascbc INT,
ascrubber INT,
asean INT,
asecna INT,
asef INT,
aspac INT,
ato INT,
atpc INT,
au INT,
avrdc INT,
afdb INT,
afropda INT,
africarice INT,
africare INT,
amcc INT,
andean INT,
aralsea INT,
articc INT,
asdb INT,
baltbat INT,
bc INT,
bcsc INT,
benelux INT,
biisef INT,
bionet INT,
bipm INT,
bis INT,
bndp INT,
bobp INT,
bonn INT,
borgip INT,
bs INT,
bsec INT,
caad INT,
caarc INT,
cab INT,
cabi INT,
cacb INT,
caci INT,
caec INT,
caecc INT,
caipa INT,
cames INT,
camrsd INT,
camsf INT,
caricom INT,
carifta INT,
carii INT,
catc INT,
cbfp INT,
cbi INT,
cbss INT,
ccnr INT,
ccom INT,
ccpa INT,
ccomm INT,
cdb INT,
ceao INT,
cec INT,
ceepn INT,
cefta INT,
cei INT,
celc INT,
cemac INT,
cento INT,
cepgl INT,
cern INT,
cfatf INT,
cfc INT,
chstea INT,
cica INT,
cifc INT,
cilss INT,
cima INT,
cis INT,
cmaec INT,
cmaoc INT,
cmea INT,
cmhasg INT,
coe INT,
colombo INT,
comesa INT,
confejes INT,
coptac INT,
cosave INT,
cpab INT,
cpsc INT,
cpu INT,
cslf INT,
csto INT,
ctcaf INT,
cto INT,
cwgc INT,
cxc INT,
cfrn INT,
comab INT,
comsec INT,
corg INT,
d8 INT,
dbgls INT,
dlcoea INT,
danube INT,
eac INT,
eacm INT,
eacso INT,
eadb INT,
eaec INT,
eapc INT,
eapo INT,
ebrd INT,
ecb INT,
ecca INT,
eccas INT,
eccb INT,
eccd INT,
eccm INT,
eccpif INT,
eco INT,
ecowas INT,
ecpta INT,
ecsc INT,
eec INT,
efcc INT,
efilwc INT,
efta INT,
eib INT,
eip INT,
eipa INT,
eldo INT,
emb INT,
embc INT,
embl INT,
emi INT,
emppo INT,
epa INT,
epfsc INT,
epo INT,
epu INT,
eria INT,
esa INT,
eso INT,
esro INT,
etf INT,
eu INT,
eufmd INT,
euramet INT,
euratom INT,
eurocontrol INT,
eurofima INT,
euromet INT,
entente INT,
fao INT,
fdiplac INT,
fec INT,
g15 INT,
g24 INT,
g3 INT,
gatt INT,
gbact INT,
gcc INT,
gcrsnc INT,
gef INT,
geo INT,
ghsi INT,
glacsec INT,
goic INT,
hcpil INT,
iabe INT,
iabath INT,
iacb INT,
iaci INT,
iacs INT,
iacss INT,
iacw INT,
iadb INT,
iadefb INT,
iaea INT,
iafc INT,
iahc INT,
iaias INT,
iaic INT,
iaigc INT,
iaii INT,
ialong INT,
iamlo INT,
iaphy INT,
iara INT,
iarhc INT,
iaradio INT,
iaruhr INT,
ias INT,
iasaj INT,
iatb INT,
iatsj INT,
iattc INT,
iba INT,
ibcs INT,
ibe INT,
ibec INT,
ibi INT,
ibier INT,
ibpmp INT,
ibrd INT,
icac INT,
icai INT,
icao INT,
icamo INT,
icc INT,
iccec INT,
iccilmb INT,
icco INT,
iccrom INT,
iccs INT,
iccslt INT,
icdr INT,
ices INT,
icfam INT,
ichrb INT,
icmmp INT,
icnc INT,
icnwaf INT,
icprp INT,
icptu INT,
icri INT,
icrpbc INT,
icse INT,
icseaf INT,
icsg INT,
ictm INT,
icfo INT,
ichemo INT,
icivdo INT,
icomo INT,
idc INT,
iea INT,
iec INT,
ies INT,
iexb INT,
ifad INT,
ifc INT,
ifca INT,
igad INT,
igc INT,
igcc INT,
iho INT,
iia INT,
iicom INT,
iie INT,
iif INT,
iifeo INT,
iiwee INT,
ijo INT,
ilo INT,
ilzsg INT,
imbslav INT,
imc INT,
imf INT,
imi INT,
imo INT,
imso INT,
incap INT,
infofish INT,
infsmk INT,
inpfc INT,
inro INT,
insg INT,
intelsat INT,
interpol INT,
ioathre INT,
iocom INT,
ioez INT,
iolm INT,
iomig INT,
iooc INT,
iopcf INT,
ioph INT,
iorarc INT,
iocc INT,
ipc INT,
ipi INT,
ipedi INT,
ipentc INT,
iphyl INT,
iprizec INT,
irena INT,
irlcs INT,
iro INT,
irsg INT,
iru INT,
isa INT,
isb INT,
isdb INT,
ishrest INT,
isrbc INT,
isupt INT,
isuc INT,
itc INT,
itcc INT,
itcle INT,
itpa INT,
itro INT,
itto INT,
itu INT,
itvrc INT,
iuic INT,
iupct INT,
iupip INT,
iuplaw INT,
iupnvp INT,
iupr INT,
ivwo INT,
iwsg INT,
iwhale INT,
iocean INT,
jalaao INT,
jinr INT,
jnolcrh INT,
lacac INT,
lacp INT,
laeo INT,
lafdo INT,
lafta INT,
laia INT,
laiec INT,
latin INT,
lcbc INT,
lgida INT,
loas INT,
lon INT,
maocn INT,
marri INT,
mcpttc INT,
mcwcasm INT,
mfo INT,
miga INT,
mru INT,
mwn INT,
mercosur INT,
montreal INT,
nacap INT,
nafo INT,
nafta INT,
nam INT,
nappo INT,
nasco INT,
nato INT,
ncm INT,
ncrr INT,
nctr INT,
ndf INT,
neafc INT,
nerc INT,
nib INT,
npafc INT,
npfsc INT,
npi INT,
nrc INT,
ntsc INT,
nvc INT,
nwhf INT,
nordc INT,
oapec INT,
oas INT,
oau INT,
ocam INT,
ocas INT,
occedca INT,
ocr INT,
oecd INT,
oecs INT,
oeec INT,
oic INT,
oiv INT,
omdkr INT,
omvg INT,
opanal INT,
opec INT,
osce INT,
oslo INT,
ospar INT,
otif INT,
pahc INT,
paho INT,
paigh INT,
pap INT,
papu INT,
pc INT,
pca INT,
pcb INT,
pcsp INT,
ped INT,
piarc INT,
pibac INT,
pices INT,
pics INT,
pif INT,
pipd INT,
pmaesa INT,
psnarco INT,
ptasea INT,
puasp INT,
rascom INT,
rcaela INT,
rcc INT,
rcfc INT,
recsa INT,
rimmo INT,
rioppah INT,
riogroup INT,
radiou INT,
repcom INT,
saafa INT,
saarc INT,
sacep INT,
sacu INT,
sadc INT,
sadcc INT,
sami INT,
sartc INT,
sca INT,
scaf INT,
sch INT,
schengen INT,
sco INT,
seameo INT,
seato INT,
segib INT,
sela INT,
sica INT,
sieca INT,
sittdec INT,
spc INT,
srdo INT,
swapu INT,
swpd INT,
sugu INT,
tcrmg INT,
turksoy INT,
uasc INT,
ubec INT,
udeac INT,
uemoa INT,
uiucv INT,
ukdwd INT,
um INT,
umac INT,
umoa INT,
un INT,
unesco INT,
unido INT,
unidroit INT,
upu INT,
usp INT,
valdivia INT,
vasab INT,
waec INT,
wahc INT,
waho INT,
wcdc INT,
wco INT,
weu INT,
who INT,
wipo INT,
wmo INT,
wnf INT,
wpact INT,
wto INT,
wtouro INT,
wassen INT,
PRIMARY KEY (ccode, year));